### PR TITLE
Moved over aead code from @bendoerr 's pull  request into one single …

### PR DESCRIPTION
**Pull request by Cictrone**
…branch

### CODE REVIEW

**Comment by Cictrone** [comment]
as stated in the commit this is just @bendoerr 's code for aead put into one pull request

**Comment by Cictrone** [comment]
@abstractj I just wanted to make sure you saw this

**Comment by abstractj** [comment]
@Cictrone yep, that's the purpose of GH notifications ;)

**Comment by bendoerr** [comment]
Let me know if I can do anything to help out. Kalium is a great project and has helped me integrate libsodium into a bunch of personal projects.

**Comment by abstractj** [comment]
@bendoerr @Cictrone landed here https://github.com/abstractj/kalium/commit/c7db58c1bfa0d8e88d34a9fb69abed68341195fb. @Cictrone I just added the original author back, and the purpose of this commit. But I made sure to give the props to you at the comments. Let me know, just in case you're not ok with this.

**Comment by Cictrone** [comment]
nope this is fine, thanks :)

**Pull request closed without merging**
