### PR TITLE
Add additional ed25519 JNI hooks

### PR DESCRIPTION
**Pull request by jreckner**
I found the following methods helpful for my work using ed25519. I was using libsodium 1.0.3

### CODE REVIEW

**Comment by abstractj** [comment]
@jreckner thanks for this. Would you mind to add unit tests? I would appreciate that if possible.

**Comment by jreckner** [comment]
@abstractj, I won't mind if there were some examples I could follow for the other methods in the interface src/main/java/org/abstractj/kalium/NaCl.java. I am far from being an expert, these lines look to simply directly expose libsodiums API ( in Sodium.class) to your interface also called Sodium.

**Comment by abstractj** [comment]
@jreckner all the examples are available here https://github.com/abstractj/kalium/tree/master/src/test/java/org/abstractj/kalium

**Comment by abstractj** [comment]
@jreckner I'm closing it for now, feel free to reopen if you would like to move forward.

**Pull request closed without merging**
